# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rowCorCpp <- function(idxX, idxY, X, Y) {
    .Call(`_scMEGA_rowCorCpp`, idxX, idxY, X, Y)
}

