# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: render-rmarkdown
run-name: Rendering rmarkdown files
on: [push]


jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install libraries
        run: |
          sudo apt-get install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev libfreetype6-dev libfontconfig1-dev
      - name: Install dependencies
        run: |
          install.packages("textshaping")
          install.packages("curl")
          install.packages("devtools")
          install.packages("BiocManager")
          install.packages("rmarkdown")
          devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
          devtools::install_github("satijalab/seurat", "seurat5")
          install.packages("Signac")
        shell: Rscript {0}
      - name: Install pacakges for tutorial
        run: |
          devtools::install_github("CostaLab/scMEGA")
          devtools::install_github("immunogenomics/harmony")
          BiocManager::install("Nebulosa")
          BiocManager::install("JASPAR2020")
          BiocManager::install("TFBSTools")
          BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
          BiocManager::install("EnsDb.Hsapiens.v86")
          install.pacakges('ggraph')
          install.pacakges('igraph')
          devtools::install_github("CostaLab/MOJITOO")
        shell: Rscript {0}
      - name: Render Rmarkdown files
        run: |
          pkgdown::build_site()
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "Re-build Rmarkdown files"
          git push origin || echo "No changes to commit"
